// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP for Homee": {
        "en": "IP for Homee",
        "de": "IP für Zuhause",
        "ru": "IP для дома",
        "pt": "IP para casa",
        "nl": "IP voor thuis",
        "fr": "IP pour la maison",
        "it": "IP per casa",
        "es": "IP para el hogar",
        "pl": "IP dla domu"
    }
};
